(()=>{'use strict';
const T=THREE, root=document.getElementById('game');
const scene=new T.Scene();scene.background=new T.Color(0x748a99);scene.fog=new T.Fog(0x748a99,28,105);
const camera=new T.PerspectiveCamera(78,innerWidth/innerHeight,.05,180);camera.rotation.order='YXZ';
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;root.appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0xe9f4ff,0x18212a,1.65));const sun=new T.DirectionalLight(0xffffff,2.1);sun.position.set(20,35,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const clock=new T.Clock();const keys={};let yaw=0,pitch=0,locked=false,running=false,paused=false,phase='menu',mode='ai',round=1,roundWins=0,enemyWins=0,roundTime=55,buyTime=5,coins=500,fireHeld=false,aiming=false,shootCD=0,reloadT=0,dashCD=0,jumpVel=0,slideT=0,buildMode=false,buildRot=0,shake=0,world=[],builds=[],enemy=null,weaponIndex=0,ammo=[],killFeed=[],roundTransition=null;
const weapons=[
{name:'USP',price:500,mag:12,reserve:48,damage:34,rate:4.5,reload:1.25,range:90,spread:.006,color:0x252a2e,icon:'◼'},
{name:'SMG',price:900,mag:30,reserve:120,damage:21,rate:13,reload:1.35,range:75,spread:.018,color:0x30363b,icon:'▰'},
{name:'ASSAULT RIFLE',price:1400,mag:24,reserve:96,damage:29,rate:9,reload:1.5,range:105,spread:.012,color:0x252b30,icon:'▰'},
{name:'SHOTGUN',price:2000,mag:6,reserve:30,damage:17,rate:1.25,reload:1.55,range:42,spread:.055,pellets:8,color:0x272a2e,icon:'◆'}];
const player={pos:new T.Vector3(0,1.75,10),hp:100,armor:50,alive:true,kills:0,deaths:0,bob:0,onGround:true,vel:new T.Vector3(),owned:new Set([0])};
const arena={size:32,blocks:[[-9,1.5,0,2,3,10],[9,1.5,0,2,3,10],[0,1.2,-7,8,2.4,2],[0,1.2,7,8,2.4,2],[-5,.8,-5,2,1.6,2],[5,.8,5,2,1.6,2]]};
const viewGun=new T.Group();viewGun.position.set(.38,-.34,-.78);camera.add(viewGun);scene.add(camera);
function mat(c,r=.7,m=.05){return new T.MeshStandardMaterial({color:c,roughness:r,metalness:m});}
function addBox(x,y,z,w,h,d,c,collide=true){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c,.7,.08));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);if(collide)world.push({x,z,w,d,h,mesh:m});return m;}
function clearWorld(){for(const o of [...scene.children])if(o!==camera&&o!==sun&&!o.isLight)scene.remove(o);world=[];builds=[];document.getElementById('labels').innerHTML='';}
function makeArena(){clearWorld();const s=arena.size;addBox(0,-.25,0,s,.5,s,0x3c464e,false);addBox(0,2,-s/2-.5,s,4,1,0x1c232a);addBox(0,2,s/2+.5,s,4,1,0x1c232a);addBox(-s/2-.5,2,0,1,4,s,0x1c232a);addBox(s/2+.5,2,0,1,4,s,0x1c232a);for(const b of arena.blocks)addBox(...b,0x56636c,true);for(let x=-14;x<=14;x+=2)addBox(x,.02,0,.025,.05,s-2,0x69747b,false);for(const p of [[-12,.65,-11],[12,.65,-11],[-12,.65,11],[12,.65,11]])addBox(p[0],p[1],p[2],1.3,1.3,1.3,0x8a6244,true);}
function blocked(x,z,r=.48){if(Math.abs(x)>arena.size/2-1-r||Math.abs(z)>arena.size/2-1-r)return true;for(const o of world)if(Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r)return true;return false;}
function moveXZ(pos,dx,dz,r=.48){let nx=pos.x+dx,nz=pos.z+dz;if(!blocked(nx,pos.z,r))pos.x=nx;if(!blocked(pos.x,nz,r))pos.z=nz;}
function forward(){return new T.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));}function right(){return new T.Vector3(Math.cos(yaw),0,-Math.sin(yaw));}
function weaponModel(type,first=false){const g=new T.Group(),w=weapons[type];const body=new T.Mesh(new T.BoxGeometry(first?.22:.4,first?.16:.27,first?.72:1.35),mat(w.color,.32,.72));body.position.set(0,0,-.42);g.add(body);const slide=new T.Mesh(new T.BoxGeometry(first?.18:.3,first?.11:.14,first?.5:.95),mat(0x11161a,.24,.9));slide.position.set(0,.14,-.47);g.add(slide);const barrel=new T.Mesh(new T.CylinderGeometry(first?.035:.06,first?.04:.065,first?.38:.78,10),mat(0x0b0e10,.22,.9));barrel.rotation.x=Math.PI/2;barrel.position.set(0,.03,-.88);g.add(barrel);const grip=new T.Mesh(new T.BoxGeometry(first?.12:.16,first?.29:.33,first?.15:.2),mat(0x14181b));grip.position.set(0,-.2,-.08);grip.rotation.x=-.2;g.add(grip);if(type>0){const mg=new T.Mesh(new T.BoxGeometry(.14,.36,.24),mat(0x101417,.45,.45));mg.position.set(0,-.24,-.31);mg.rotation.x=.25;g.add(mg);}if(type===3){const pump=new T.Mesh(new T.BoxGeometry(.23,.12,.36),mat(0x1a1e21));pump.position.set(0,-.1,-.62);g.add(pump);}return g;}
function humanoid(){const g=new T.Group(),parts={};parts.pelvis=new T.Mesh(new T.BoxGeometry(.58,.32,.36),mat(0x20262b));parts.pelvis.position.y=.82;g.add(parts.pelvis);parts.torso=new T.Mesh(new T.BoxGeometry(.72,.84,.4),mat(0x8f2830));parts.torso.position.y=1.38;g.add(parts.torso);parts.vest=new T.Mesh(new T.BoxGeometry(.75,.5,.43),mat(0x421c20,.75,.15));parts.vest.position.set(0,1.4,-.02);g.add(parts.vest);parts.head=new T.Mesh(new T.SphereGeometry(.25,12,8),mat(0xc98d69));parts.head.position.y=2.05;g.add(parts.head);const helmet=new T.Mesh(new T.SphereGeometry(.28,12,7,0,Math.PI*2,0,Math.PI*.55),mat(0x1b2228,.5,.25));helmet.position.y=2.14;g.add(helmet);parts.armL=limb(.16,.7,.17,0x8f2830);parts.armR=limb(.16,.7,.17,0x8f2830);parts.legL=limb(.19,.78,.2,0x20262b);parts.legR=limb(.19,.78,.2,0x20262b);parts.armL.position.set(-.46,1.38,0);parts.armR.position.set(.46,1.38,0);parts.legL.position.set(-.2,.43,0);parts.legR.position.set(.2,.43,0);g.add(parts.armL,parts.armR,parts.legL,parts.legR);const gun=weaponModel(0);gun.scale.set(.42,.42,.42);gun.position.set(.42,1.2,-.34);g.add(gun);g.userData.parts=parts;return g;}
function limb(w,h,d,c){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.castShadow=true;return m;}
function spawnEnemy(){if(enemy?.mesh)scene.remove(enemy.mesh);const mesh=humanoid();mesh.position.set(0,0,-10);scene.add(mesh);enemy={mesh,pos:mesh.position,hp:100,armor:30,alive:true,phase:0,think:.1,shoot:.8,reaction:.7,weapon:Math.min(round-1,2),targetPos:new T.Vector3(0,0,10),name:mode==='online'?'PLAYER-OPPONENT':'AI WOLF',strafeDir:Math.random()<.5?-1:1,dodgeT:0,burst:0};}
function lineClear(a,b){const start=new T.Vector3(a.x,1.45,a.z),d=new T.Vector3(b.x-start.x,0,b.z-start.z),len=d.length();if(!len)return true;d.normalize();const ray=new T.Raycaster(start,d,0,len);return ray.intersectObjects(world.map(o=>o.mesh),false).length===0;}
function applyDamage(v,amount,att){let ab=Math.min(v.armor||0,amount*.5);v.armor=(v.armor||0)-ab;v.hp-=amount-ab;if(v===player){document.getElementById('damage').style.opacity=.55;setTimeout(()=>document.getElementById('damage').style.opacity=0,100);shake=.07;}if(v.hp<=0){if(v===player)loseRound();else winRound();}}
function hitscan(origin,dir,w,owner){const ray=new T.Raycaster(origin,dir,0,w.range);if(owner===player){if(!enemy?.alive)return false;const hits=ray.intersectObjects(enemy.mesh.children.filter(x=>x.isMesh),false);if(hits.length){applyDamage(enemy,w.damage,player);hitMarker();return true;}}else{const pbox=new T.Mesh(new T.BoxGeometry(.8,2.2,.6));pbox.position.set(player.pos.x,1.1,player.pos.z);pbox.updateMatrixWorld();const hit=ray.intersectObject(pbox,false)[0];if(hit){applyDamage(player,w.damage,enemy);return true;}}return false;}
function hitMarker(){const h=document.getElementById('hitmarker');h.style.opacity=1;setTimeout(()=>h.style.opacity=0,70);}
function shoot(){if(!player.alive||phase!=='fight'||reloadT>0||shootCD>0)return;const w=weapons[weaponIndex],a=ammo[weaponIndex];if(a.m<=0){reload();return}a.m--;shootCD=1/w.rate;const o=camera.position.clone(),base=aimAssist(forward());for(let i=0;i<(w.pellets||1);i++){const d=base.clone();d.x+=(Math.random()-.5)*w.spread;d.y+=(Math.random()-.5)*w.spread;d.z+=(Math.random()-.5)*w.spread;hitscan(o,d.normalize(),w,player);}viewGun.position.z=-.73;shake=.028;setTimeout(()=>viewGun.position.z=-.78,45);updateHUD();}
function reload(){const w=weapons[weaponIndex],a=ammo[weaponIndex];if(reloadT>0||a.m>=w.mag||a.r<=0)return;reloadT=w.reload;}
function dash(){if(phase!=='fight'||!player.alive||dashCD>0)return;dashCD=1.0;const d=forward();moveXZ(player.pos,d.x*5.2,d.z*5.2,.48);player.vel.copy(d).multiplyScalar(7);shake=.035;}
function jump(){if(phase==='fight'&&player.alive&&player.onGround){jumpVel=8.2;player.onGround=false;}}
function placeBuild(){if(!buildMode||phase!=='fight'||!player.alive)return;const p=player.pos.clone().add(forward().multiplyScalar(3));const horizontal=buildRot%2===0,w=horizontal?3.4:.55,d=horizontal?.55:3.4;if(blocked(p.x,p.z,.3)||Math.abs(p.x)>14||Math.abs(p.z)>14)return;const m=addBox(p.x,1.5,p.z,w,3,d,0x657782,true);m.material.transparent=true;m.material.opacity=.9;builds.push({mesh:m});buildMode=false;document.getElementById('build').classList.remove('on');}
function updatePlayer(dt){
 if(!player.alive||phase!=='fight')return;
 const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0);
 let v=new T.Vector3();
 if(f||s){v.copy(forward()).multiplyScalar(f).add(right().multiplyScalar(s)).normalize();let speed=(keys.ShiftLeft||keys.ShiftRight)?13:8.5;if(aiming)speed*=.72;if(slideT>0)speed=12;moveXZ(player.pos,v.x*speed*dt,v.z*speed*dt,.48);player.bob+=dt*(speed>10?15:10);}
 if(player.vel.lengthSq()>.1){moveXZ(player.pos,player.vel.x*dt,player.vel.z*dt,.48);player.vel.multiplyScalar(Math.pow(.03,dt));}
 jumpVel-=22*dt;player.pos.y+=jumpVel*dt;if(player.pos.y<=1.75){player.pos.y=1.75;jumpVel=0;player.onGround=true}
 if(keys.KeyC&&player.onGround&&!(keys.ControlLeft||keys.ControlRight)){slideT=Math.max(slideT,.22)}
 if(slideT>0){slideT-=dt;const d=forward();moveXZ(player.pos,d.x*11*dt,d.z*11*dt,.48)}
 dashCD=Math.max(0,dashCD-dt);
 camera.position.copy(player.pos);camera.position.y+=Math.sin(player.bob)*.035;
 camera.fov += ((aiming?58:78)-camera.fov)*Math.min(1,dt*14);camera.updateProjectionMatrix();camera.rotation.set(pitch,yaw,0);
 viewGun.rotation.x=-pitch*.05;viewGun.position.x+=(aiming?.30:.38-viewGun.position.x)*Math.min(1,dt*12);viewGun.position.y+=(aiming?-.30:-.34-viewGun.position.y)*Math.min(1,dt*12);
 if(fireHeld)shoot();
}
function aimAssist(dir){
 if(!aiming||!enemy?.alive)return dir;
 const to=enemy.pos.clone().add(new T.Vector3(0,1.35,0)).sub(camera.position),dist=to.length();if(dist>55)return dir;
 const nd=to.normalize(),dot=dir.dot(nd);
 if(dot>.975){const strength=.16*(1-dist/55);return dir.lerp(nd,strength).normalize()}return dir;
}
function updateEnemy(dt){
 if(!enemy||!enemy.alive)return;
 enemy.phase+=dt*9;enemy.think-=dt;enemy.shoot-=dt;enemy.dodgeT-=dt;
 const dist=enemy.pos.distanceTo(player.pos),visible=player.alive&&dist<32&&lineClear(enemy.pos,player.pos);
 if(enemy.think<=0){
  enemy.think=.14+Math.random()*.16;
  if(Math.random()<.12)enemy.strafeDir*=-1;
  enemy.targetPos=visible?player.pos.clone():new T.Vector3((Math.random()-.5)*20,0,(Math.random()-.5)*20);
 }
 const dir=enemy.targetPos.clone().sub(enemy.pos);dir.y=0;
 if(dir.length()>3){dir.normalize();const strafe=new T.Vector3(-dir.z,0,dir.x).multiplyScalar(Math.sin(enemy.phase*1.35)*.85*enemy.strafeDir);const sp=visible?2.7:3.7;moveXZ(enemy.pos,(dir.x+strafe.x)*dt*sp,(dir.z+strafe.z)*dt*sp,.48);}
 if(visible&&dist<18&&enemy.dodgeT<=0&&Math.random()<dt*.7){enemy.dodgeT=.7;enemy.strafeDir*=-1;}
 enemy.mesh.rotation.y=Math.atan2(-dir.x,-dir.z);
 const p=enemy.mesh.userData.parts,s=Math.sin(enemy.phase)*.65;p.legL.rotation.x=s;p.legR.rotation.x=-s;p.armL.rotation.x=-s*.18;p.armR.rotation.x=s*.18;
 if(visible&&enemy.shoot<=0){enemy.shoot=.48+Math.random()*.5;const accuracy=Math.max(.28,.82-dist/50);if(Math.random()<accuracy)enemyShoot();}
 updateLabel();
}
function enemyShoot(){const w=weapons[enemy.weapon];const o=enemy.pos.clone();o.y=1.55;const d=player.pos.clone().add(new T.Vector3(0,.2,0)).sub(o).normalize();hitscan(o,d,w,enemy);}
function updateLabel(){let t=enemy.mesh.userData.tag;if(!t){t=document.createElement('div');t.className='nameplate enemy';document.getElementById('labels').appendChild(t);enemy.mesh.userData.tag=t}const v=enemy.mesh.position.clone();v.y=2.8;v.project(camera);t.style.transform=`translate(${(v.x*.5+.5)*innerWidth}px,${(-v.y*.5+.5)*innerHeight}px) translate(-50%,-50%)`;t.textContent=enemy.name+'  '+Math.max(0,Math.ceil(enemy.hp))+' HP';t.style.opacity=enemy.alive&&v.z<1?1:0;}
function resetRound(){
 makeArena();player.pos.set(0,1.75,10);player.hp=100;player.armor=50;player.alive=true;player.vel.set(0,0,0);yaw=0;pitch=0;dashCD=0;reloadT=0;shootCD=0;aiming=false;fireHeld=false;document.getElementById('cross').classList.remove('aiming');buildMode=false;builds=[];spawnEnemy();ammo=weapons.map(w=>({m:w.mag,r:w.reserve}));phase='shop';buyTime=5;
 document.getElementById('shop').classList.remove('hidden');renderShop();document.getElementById('hud').classList.remove('hidden');document.getElementById('result').classList.add('hidden');updateHUD();
 showRoundTitle(round);
}
function beginMatch(m){mode=m;round=1;roundWins=0;enemyWins=0;coins=500;player.owned=new Set();weaponIndex=0;running=true;paused=false;document.getElementById('menu').classList.add('hidden');document.getElementById('modeMenu').classList.add('hidden');document.getElementById('queue').classList.add('hidden');resetRound();}
function requestLock(){renderer.domElement.requestPointerLock?.();}
function playThssh(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=new AC();const o=ac.createOscillator(),g=ac.createGain();o.type='sawtooth';o.frequency.setValueAtTime(170,ac.currentTime);o.frequency.exponentialRampToValueAtTime(55,ac.currentTime+.22);g.gain.setValueAtTime(.0001,ac.currentTime);g.gain.exponentialRampToValueAtTime(.22,ac.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.24);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.25);setTimeout(()=>ac.close?.(),400)}catch(e){}}
function showRoundTitle(n){const el=document.getElementById('roundState');if(!el)return;el.textContent=n+'th ROUND';if(n===1)el.textContent='1st ROUND';else if(n===2)el.textContent='2nd ROUND';else if(n===3)el.textContent='3rd ROUND';el.classList.add('roundPop');playThssh();setTimeout(()=>el.classList.remove('roundPop'),1000);}
function startFight(){if(!player.owned.has(0)){if(coins>=weapons[0].price){coins-=weapons[0].price;player.owned.add(0);weaponIndex=0;}else{coins=0;player.owned.add(0);weaponIndex=0;}}phase='fight';roundTime=55;document.getElementById('shop').classList.add('hidden');requestLock();feed('FIGHT!','good');updateHUD();}
function awardRound(won){const reward=won?700:100;coins+=reward;return reward;}
function finishMatch(){const won=roundWins>enemyWins;phase='result';document.exitPointerLock?.();document.getElementById('resultTitle').textContent=won?'MATCH WON':'MATCH LOST';document.getElementById('resultSub').textContent='5 ROUNDS COMPLETE  •  '+roundWins+' — '+enemyWins+'  •  '+coins+' COINS';document.getElementById('nextRound').textContent='BACK TO MENU';document.getElementById('result').classList.remove('hidden');}
function scheduleNextRound(){if(round>=5){finishMatch();return}round++;roundTransition=setTimeout(()=>resetRound(),850);}
function winRound(){if(phase!=='fight')return;phase='transition';roundWins++;coins+=awardRound(true);player.kills++;enemy.alive=false;enemy.mesh.visible=false;document.exitPointerLock?.();feed('ROUND WON • +'+(round===1?700:700)+' COINS','good');if(round>=5){finishMatch();return}scheduleNextRound();}
function loseRound(){if(phase!=='fight')return;phase='transition';enemyWins++;player.deaths++;player.alive=false;document.exitPointerLock?.();coins+=awardRound(false);feed('ROUND LOST • +'+(round===1?100:100)+' COINS','bad');if(round>=5){finishMatch();return}scheduleNextRound();}
function nextRound(){if(round>=5){leaveToMenu();return}if(roundTransition){clearTimeout(roundTransition);roundTransition=null}round++;resetRound();}
function leaveToMenu(){if(roundTransition)clearTimeout(roundTransition);running=false;phase='menu';document.exitPointerLock?.();document.getElementById('hud').classList.add('hidden');document.getElementById('result').classList.add('hidden');document.getElementById('pause').classList.add('hidden');document.getElementById('shop').classList.add('hidden');document.getElementById('menu').classList.remove('hidden');}
function renderShop(){const box=document.getElementById('gunCards');document.getElementById('coins').textContent=coins;box.innerHTML='';weapons.forEach((w,i)=>{const owned=player.owned.has(i),selected=i===weaponIndex,can=coins>=w.price||owned;const d=document.createElement('div');d.className='gunCard '+(selected?'selected':'');d.innerHTML=`<div class="gunIcon">${w.icon}</div><h3>${w.name}</h3><div class="stats">PRICE ${w.price} · DMG ${w.damage} · MAG ${w.mag}<br>FIRE ${w.rate}/s · RANGE ${w.range}</div><button ${can?'':'disabled'}>${owned?(selected?'EQUIPPED':'EQUIP'):'BUY '+w.price}</button>`;d.querySelector('button').onclick=()=>{if(!owned){if(coins<w.price)return;coins-=w.price;player.owned.add(i)}weaponIndex=i;viewGun.clear();viewGun.add(weaponModel(i,true));renderShop();updateHUD()};box.appendChild(d)});}
function updateHUD(){const w=weapons[weaponIndex],a=ammo[weaponIndex]||{m:w.mag,r:w.reserve};document.getElementById('weapon').textContent=w.name;document.getElementById('mag').textContent=a.m;document.getElementById('reserve').textContent=a.r;document.getElementById('hp').textContent=Math.max(0,Math.ceil(player.hp))+' HP';document.getElementById('armor').textContent=Math.max(0,Math.ceil(player.armor))+' ARM';document.getElementById('hpbar').style.width=Math.max(0,player.hp)+'%';document.getElementById('dash').textContent=dashCD>0?dashCD.toFixed(1)+'s':'READY';document.getElementById('roundScore').textContent=roundWins+' — '+enemyWins;}
function feed(t,c='neutral'){killFeed.unshift({t,c});killFeed.splice(5);document.getElementById('feed').innerHTML=killFeed.map(x=>`<div class="msg ${x.c}">${x.t}</div>`).join('');}
function setWeapon(i){if(player.owned.has(i)){weaponIndex=i;viewGun.clear();viewGun.add(weaponModel(i,true));updateHUD();}}
function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.05);if(running&&!paused){if(phase==='shop'){buyTime=Math.max(0,buyTime-dt);document.getElementById('buyTimer').textContent=buyTime.toFixed(1);if(buyTime<=0)startFight()}if(phase==='fight'){roundTime-=dt;if(roundTime<=0){roundTime=0;loseRound()}shootCD=Math.max(0,shootCD-dt);if(reloadT>0){reloadT-=dt;if(reloadT<=0){const w=weapons[weaponIndex],a=ammo[weaponIndex],need=w.mag-a.m,take=Math.min(need,a.r);a.m+=take;a.r-=take}}updatePlayer(dt);updateEnemy(dt);document.getElementById('roundTimer').textContent='00:'+String(Math.ceil(roundTime)).padStart(2,'0');updateHUD()}}if(shake>0){shake-=dt;camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'&&!e.repeat)jump();if(e.code==='KeyR'&&!e.repeat)reload();if((e.code==='ControlLeft'||e.code==='ControlRight')&&!e.repeat)dash();if(e.code==='KeyQ'&&!e.repeat){buildMode=!buildMode;document.getElementById('build').classList.toggle('on',buildMode)}if(e.code==='KeyE'&&buildMode)buildRot++;if(e.code==='Digit1')setWeapon(0);if(e.code==='Digit2')setWeapon(1);if(e.code==='Digit3')setWeapon(2);if(e.code==='Digit4')setWeapon(3);if(e.code==='Escape'&&running&&phase==='fight'){paused=true;document.getElementById('pause').classList.remove('hidden');document.exitPointerLock?.()}});
addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{for(const k in keys)keys[k]=false;fireHeld=false;aiming=false;document.getElementById('cross').classList.remove('aiming')});addEventListener('mousedown',e=>{if(!running||paused)return;if(phase==='fight'&&!locked)requestLock();if(e.button===0){if(buildMode)placeBuild();else{fireHeld=true;shoot()}}if(e.button===2){if(buildMode){buildMode=false;document.getElementById('build').classList.remove('on')}aiming=true;requestLock();document.getElementById('cross').classList.add('aiming')}});addEventListener('mouseup',e=>{if(e.button===0)fireHeld=false;if(e.button===2){aiming=false;document.getElementById('cross').classList.remove('aiming')}});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(!locked||paused||phase!=='fight'||!player.alive)return;const sens=.0022;yaw-=e.movementX*sens;pitch-=e.movementY*sens;pitch=Math.max(-1.3,Math.min(1.3,pitch))});document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===renderer.domElement);
// UI
const show=x=>document.getElementById(x).classList.remove('hidden'),hide=x=>document.getElementById(x).classList.add('hidden');document.getElementById('lonewolf').onclick=()=>{hide('menu');show('modeMenu')};document.getElementById('fightAI').onclick=()=>beginMatch('ai');document.getElementById('fightOnline').onclick=()=>{hide('modeMenu');show('queue');document.getElementById('onlineNote').textContent='';let n=0;const q=setInterval(()=>{n++;document.getElementById('queueText').textContent='Searching… '+(n*20)+'%';if(n>=5){clearInterval(q);document.getElementById('queueTitle').textContent='NO LIVE PLAYER FOUND';document.getElementById('queueText').textContent='Starting a practice opponent so the mode remains playable offline.';setTimeout(()=>beginMatch('online'),800)}},500)};document.getElementById('cancelQueue').onclick=()=>{hide('queue');show('modeMenu')};document.querySelector('[data-back="menu"]').onclick=()=>{hide('modeMenu');show('menu')};document.getElementById('tdm').onclick=()=>alert('Team Arena is kept for the full arena build. 1v1 Lonewolf is the active mode.');document.getElementById('nextRound').onclick=nextRound;document.getElementById('leaveMatch').onclick=leaveToMenu;document.getElementById('resume').onclick=()=>{paused=false;hide('pause');requestLock()};document.getElementById('leavePause').onclick=leaveToMenu;
makeArena();viewGun.add(weaponModel(0,true));tick();
})();
