(()=>{'use strict';
const T=THREE,root=document.getElementById('game');
const scene=new T.Scene();scene.background=new T.Color(0x66727b);scene.fog=new T.Fog(0x66727b,35,100);
const camera=new T.PerspectiveCamera(78,innerWidth/innerHeight,.05,180);camera.rotation.order='YXZ';
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;root.appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0xe9f4ff,0x18212a,1.55));const sun=new T.DirectionalLight(0xffffff,2.0);sun.position.set(20,35,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const clock=new T.Clock(),keys={};
let yaw=0,pitch=0,locked=false,running=false,paused=false,phase='menu',mode='ai',round=1,roundWins=0,enemyWins=0,roundTime=55,buyTime=5,coins=500,fireHeld=false,aiming=false,shootCD=0,reloadT=0,jumpVel=0,slideT=0,buildMode=false,buildRot=0,shake=0,world=[],builds=[],enemy=null,weaponIndex=0,ammo=[],killFeed=[],roundTransition=null;
let audio=null,mp3={},stepT=0;
const weapons=[{name:'DESERT EAGLE',price:500,mag:7,reserve:35,damage:70,headDamage:1000,rate:3.2,reload:1.55,range:90,spread:.006,recoil:.095,color:0x34383b,icon:'◆',sound:'deagle'},{name:'SMG',price:900,mag:30,reserve:120,damage:18,headDamage:1000,rate:13,reload:1.35,range:75,spread:.018,recoil:.035,color:0x30363b,icon:'▰',sound:'smg'},{name:'ASSAULT RIFLE',price:1400,mag:24,reserve:96,damage:24,headDamage:1000,rate:9,reload:1.5,range:105,spread:.012,recoil:.045,color:0x252b30,icon:'▰',sound:'rifle'},{name:'SHOTGUN',price:2000,mag:6,reserve:30,damage:15,headDamage:1000,rate:1.25,reload:1.65,range:42,spread:.055,pellets:8,recoil:.14,color:0x272a2e,icon:'⬟',sound:'shotgun'}];
const player={pos:new T.Vector3(0,1.75,10),hp:100,armor:50,alive:true,kills:0,deaths:0,bob:0,onGround:true,vel:new T.Vector3(),owned:new Set()};
const arena={size:32};
const viewGun=new T.Group();viewGun.position.set(.38,-.34,-.78);camera.add(viewGun);scene.add(camera);
function mat(c,r=.7,m=.05){return new T.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function addBox(x,y,z,w,h,d,c,collide=true,opts={}){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c,opts.r??.7,opts.m??.08));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);if(collide)world.push({x,z,w,d,h,mesh:m});return m}
function addContainer(x,z,color,rot=0){const g=new T.Group();g.position.set(x,1.45,z);g.rotation.y=rot;const body=new T.Mesh(new T.BoxGeometry(5.4,2.9,2.4),mat(color,.72,.15));body.castShadow=body.receiveShadow=true;g.add(body);for(let i=-2;i<=2;i++){const rib=new T.Mesh(new T.BoxGeometry(.10,2.72,.12),mat(0x20262a,.6,.2));rib.position.set(i*1.02,0,-1.22);g.add(rib);const rib2=rib.clone();rib2.position.z=1.22;g.add(rib2)}scene.add(g);world.push({x,z,w:rot%Math.PI===0?5.4:2.4,d:rot%Math.PI===0?2.4:5.4,h:2.9,mesh:body});return g}
function addCrate(x,z,c=0x8a6244,s=1){return addBox(x,s*.55,z,s,s,s,c,true)}
function clearWorld(){for(const o of [...scene.children])if(o!==camera&&o!==sun&&!o.isLight)scene.remove(o);world=[];builds=[];document.getElementById('labels').innerHTML=''}
function makeArena(){clearWorld();const s=arena.size;addBox(0,-.25,0,s,.5,s,0x313a42,false);addBox(0,2,-s/2-.5,s,4,1,0x171d22);addBox(0,2,s/2+.5,s,4,1,0x171d22);addBox(-s/2-.5,2,0,1,4,s,0x171d22);addBox(s/2+.5,2,0,1,4,s,0x171d22);addContainer(-8,-6,0x9e242e,0);addContainer(8,6,0x254f9b,0);addContainer(-8,6,0x9e242e,Math.PI/2);addContainer(8,-6,0x254f9b,Math.PI/2);addContainer(0,0,0x56636c,0);addCrate(-12,-11);addCrate(12,11);addCrate(-12,11,0x59636c,.8);addCrate(12,-11,0x59636c,.8);addBox(0,-8,0,7,2,1.2,0x53606a);addBox(0,8,0,7,2,1.2,0x53606a);addBox(-5,0,0,1.2,2,7,0x4a555e);addBox(5,0,0,1.2,2,7,0x4a555e);for(let x=-14;x<=14;x+=2)addBox(x,.02,0,.025,.05,s-2,0x727b82,false)}
function blocked(x,z,r=.48){if(Math.abs(x)>arena.size/2-1-r||Math.abs(z)>arena.size/2-1-r)return true;for(const o of world)if(Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r)return true;return false}
function moveXZ(pos,dx,dz,r=.48){let nx=pos.x+dx,nz=pos.z+dz;if(!blocked(nx,pos.z,r))pos.x=nx;if(!blocked(pos.x,nz,r))pos.z=nz}
function forward(){return new T.Vector3(-Math.sin(yaw),0,-Math.cos(yaw))}function right(){return new T.Vector3(Math.cos(yaw),0,-Math.sin(yaw))}
function weaponModel(type,first=false){const g=new T.Group(),w=weapons[type],body=new T.Mesh(new T.BoxGeometry(first?.24:.4,first?.17:.27,first?.72:1.35),mat(w.color,.32,.72));body.position.set(0,0,-.42);g.add(body);const slide=new T.Mesh(new T.BoxGeometry(first?.20:.3,first?.11:.14,first?.50:.95),mat(0x11161a,.24,.9));slide.position.set(0,.14,-.47);g.add(slide);const barrel=new T.Mesh(new T.CylinderGeometry(first?.035:.06,first?.04:.065,first?.38:.78,10),mat(0x0b0e10,.22,.9));barrel.rotation.x=Math.PI/2;barrel.position.set(0,.03,-.88);g.add(barrel);const grip=new T.Mesh(new T.BoxGeometry(first?.13:.16,first?.30:.33,first?.15:.2),mat(0x14181b));grip.position.set(0,-.2,-.08);grip.rotation.x=-.2;g.add(grip);if(type>0){const mg=new T.Mesh(new T.BoxGeometry(.14,.36,.24),mat(0x101417,.45,.45));mg.position.set(0,-.24,-.31);mg.rotation.x=.25;g.add(mg)}if(type===3){const pump=new T.Mesh(new T.BoxGeometry(.23,.12,.36),mat(0x1a1e21));pump.position.set(0,-.1,-.62);g.add(pump)}return g}
function limb(w,h,d,c){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.castShadow=true;return m}
function humanoid(){const g=new T.Group(),parts={};parts.pelvis=limb(.58,.32,.36,0x20262b);parts.pelvis.position.y=.82;g.add(parts.pelvis);parts.torso=limb(.72,.84,.4,0x8f2830);parts.torso.position.y=1.38;g.add(parts.torso);parts.vest=limb(.75,.5,.43,0x421c20);parts.vest.position.set(0,1.4,-.02);g.add(parts.vest);parts.head=new T.Mesh(new T.SphereGeometry(.25,12,8),mat(0xc98d69));parts.head.name='HEAD';parts.head.userData.hitZone='head';parts.head.position.y=2.05;g.add(parts.head);const helmet=new T.Mesh(new T.SphereGeometry(.28,12,7,0,Math.PI*2,0,Math.PI*.55),mat(0x1b2228,.5,.25));helmet.position.y=2.14;g.add(helmet);parts.armL=limb(.16,.7,.17,0x8f2830);parts.armR=limb(.16,.7,.17,0x8f2830);parts.legL=limb(.19,.78,.2,0x20262b);parts.legR=limb(.19,.78,.2,0x20262b);parts.armL.position.set(-.46,1.38,0);parts.armR.position.set(.46,1.38,0);parts.legL.position.set(-.2,.43,0);parts.legR.position.set(.2,.43,0);g.add(parts.armL,parts.armR,parts.legL,parts.legR);const gun=weaponModel(0);gun.scale.set(.42,.42,.42);gun.position.set(.42,1.2,-.34);g.add(gun);g.userData.parts=parts;return g}
function spawnEnemy(){if(enemy?.mesh)scene.remove(enemy.mesh);const mesh=humanoid();mesh.position.set(0,0,-10);scene.add(mesh);const body=new T.Mesh(new T.BoxGeometry(.82,.98,.62));body.position.y=1.38;body.name='BODY_HITBOX';body.material.visible=false;body.userData.hitZone='body';mesh.add(body);const head=new T.Mesh(new T.SphereGeometry(.30,10,8));head.position.y=2.05;head.name='HEAD_HITBOX';head.material.visible=false;head.userData.hitZone='head';mesh.add(head);enemy={mesh,pos:mesh.position,hp:100,armor:30,alive:true,phase:0,think:.1,shoot:.8,weapon:Math.min(round-1,2),targetPos:new T.Vector3(0,0,10),name:mode==='online'?'PLAYER-OPPONENT':'AI WOLF',strafeDir:Math.random()<.5?-1:1,dodgeT:0}}
function lineClear(a,b){const start=new T.Vector3(a.x,1.45,a.z),d=new T.Vector3(b.x-start.x,0,b.z-start.z),len=d.length();if(!len)return true;d.normalize();const ray=new T.Raycaster(start,d,0,len);return ray.intersectObjects(world.map(o=>o.mesh),false).length===0}
function initAudio(){if(!audio){try{const AC=window.AudioContext||window.webkitAudioContext;audio=new AC}catch(e){}}if(audio?.state==='suspended')audio.resume();loadMP3()}
function loadMP3(){if(Object.keys(mp3).length)return;['deagle','smg','rifle','shotgun','reload','hit','headshot','round','victory','defeat','step'].forEach(n=>{const a=new Audio('assets/sounds/'+n+'.mp3');a.preload='auto';mp3[n]=a})}
function playMP3(name,volume=.8){initAudio();const a=mp3[name];if(!a)return;try{a.pause();a.currentTime=0;a.volume=volume;const q=a.play();if(q?.catch)q.catch(()=>{})}catch(e){}}
function gunSound(kind){playMP3(kind,kind==='shotgun'?.9:.72)}function reloadSound(){playMP3('reload',.65)}
function showDamageNumber(amount,head){const el=document.createElement('div');el.className='damageNumber '+(head?'head':'body');el.textContent='-'+Math.max(1,Math.round(amount));document.getElementById('labels').appendChild(el);const v=enemy.mesh.position.clone();v.y=head?2.55:2.15;v.project(camera);el.style.left=((v.x*.5+.5)*innerWidth)+'px';el.style.top=((-v.y*.5+.5)*innerHeight)+'px';setTimeout(()=>el.remove(),650);requestAnimationFrame(()=>el.classList.add('damageFly'));playMP3(head?'headshot':'hit',head?.75:.42)}
// FIX: HP subtraction uses explicit parentheses so both player and NPC health decrease correctly.
function applyDamage(v,amount,att,head=false){
 if(!v||v.alive===false)return 0;
 const raw=Math.max(0,Number(amount)||0);
 const armorBefore=Math.max(0,Number(v.armor)||0);
 const absorbed=Math.min(armorBefore,raw*.5);
 const dealt=Math.max(0,raw-absorbed);
 v.armor=Math.max(0,armorBefore-absorbed);
 v.hp=Math.max(0,(Number(v.hp)||0)-dealt);
 if(v!==player)showDamageNumber(dealt,head);
 if(v===player){document.getElementById('damage').style.opacity=.55;setTimeout(()=>document.getElementById('damage').style.opacity=0,100);shake=.07}
 updateHUD();
 if(v===enemy&&v.hp>0)updateLabel();
 if(v.hp<=0){v.hp=0;if(v===player)loseRound();else if(v===enemy&&phase==='fight')winRound(head)}
 return dealt;
}
function muzzleFlash(){const p=new T.PointLight(0xffc36a,3,4);p.position.set(.38,-.30,-1.05);camera.add(p);setTimeout(()=>camera.remove(p),45);const f=new T.Mesh(new T.ConeGeometry(.11,.32,7),new T.MeshBasicMaterial({color:0xffd36a,transparent:true,opacity:.9}));f.rotation.x=-Math.PI/2;f.position.set(.38,-.30,-1.02);camera.add(f);setTimeout(()=>camera.remove(f),55)}
function tracer(dir){const start=camera.position.clone().add(dir.clone().multiplyScalar(.5)),end=start.clone().add(dir.clone().multiplyScalar(35));const geo=new T.BufferGeometry().setFromPoints([start,end]);const line=new T.Line(geo,new T.LineBasicMaterial({color:0xffd36a,transparent:true,opacity:.9}));scene.add(line);setTimeout(()=>scene.remove(line),45)}
function hitscan(origin,dir,w,owner){const ray=new T.Raycaster(origin,dir,0,w.range);if(owner===player){if(!enemy?.alive)return false;enemy.mesh.updateMatrixWorld(true);const targets=[];enemy.mesh.traverse(o=>{if(o.isMesh&&(o.name==='HEAD_HITBOX'||o.name==='BODY_HITBOX'))targets.push(o)});const hits=ray.intersectObjects(targets,false);if(hits.length){const hit=hits[0],head=hit.object.userData.hitZone==='head';const dmg=head?w.headDamage:w.damage;applyDamage(enemy,dmg,player,head);hitMarker(head);return true}}else{const pbox=new T.Mesh(new T.BoxGeometry(.9,2.2,.7));pbox.position.set(player.pos.x,player.pos.y-.65,player.pos.z);pbox.updateMatrixWorld();const hit=ray.intersectObject(pbox,false)[0];if(hit)applyDamage(player,w.damage,enemy,false)}return false}
function hitMarker(head=false){const h=document.getElementById('hitmarker');h.textContent=head?'X':'×';h.className=head?'head':'body';h.style.opacity=1;h.style.transform='translate(-50%,-50%) scale('+(head?1.35:1)+')';setTimeout(()=>h.style.opacity=0,120);if(head)showAchievement()}
function showAchievement(){const a=document.getElementById('achievement');if(!a)return;a.classList.remove('hidden');a.classList.remove('achPop');void a.offsetWidth;a.classList.add('achPop');setTimeout(()=>a.classList.add('hidden'),2000)}
function showRoundResult(won){const r=document.getElementById('roundResult');if(!r)return;document.getElementById('roundResultTitle').textContent=won?'VICTORY':'DEFEAT';document.getElementById('roundResultSub').textContent=won?'ROUND WON':'ROUND LOST';const fill=document.getElementById('roundFill');fill.style.width='0%';r.classList.remove('hidden');r.classList.remove('resultPop');void r.offsetWidth;r.classList.add('resultPop');setTimeout(()=>fill.style.width='100%',80);setTimeout(()=>r.classList.add('hidden'),1900)}
function shoot(){if(!player.alive||phase!=='fight'||reloadT>0||shootCD>0)return;const w=weapons[weaponIndex],a=ammo[weaponIndex];if(a.m<=0){reload();return}a.m--;shootCD=1/w.rate;initAudio();gunSound(w.sound);muzzleFlash();const o=camera.position.clone(),base=aimAssist(forward());for(let i=0;i<(w.pellets||1);i++){const d=base.clone();d.x+=(Math.random()-.5)*w.spread;d.y+=(Math.random()-.5)*w.spread;d.z+=(Math.random()-.5)*w.spread;tracer(d.normalize());if(enemy?.alive)hitscan(o,d,w,player);if(!enemy?.alive)break}pitch=Math.min(1.3,pitch-w.recoil*(aiming?.55:1));viewGun.position.z=-.68;setTimeout(()=>viewGun.position.z=-.78,60);updateHUD()}
function reload(){const w=weapons[weaponIndex],a=ammo[weaponIndex];if(reloadT>0||a.m>=w.mag||a.r<=0)return;reloadT=w.reload;reloadSound();viewGun.userData.reload=0}
function startSlide(){if(!player.onGround||!player.alive||phase!=='fight')return;slideT=Math.max(slideT,.35);player.pos.y=.95}
function updatePlayer(dt){if(!player.alive||phase!=='fight')return;const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0),moving=!!(f||s),sprinting=(keys.ShiftLeft||keys.ShiftRight)&&f>0&&!aiming&&moving;let v=new T.Vector3();if(moving){v.copy(forward()).multiplyScalar(f).add(right().multiplyScalar(s)).normalize();let speed=sprinting?13:8.5;if(aiming)speed*=.72;if(slideT>0)speed=12;moveXZ(player.pos,v.x*speed*dt,v.z*speed*dt,.48);player.bob+=dt*(sprinting?18:11);stepT-=dt;if(stepT<=0){stepT=sprinting?.30:.48;playMP3('step',sprinting?.22:.12)}}const crouch=keys.KeyC&&!sprinting&&!slideT;const h=slideT>0||crouch?.95:1.75;jumpVel-=22*dt;player.pos.y+=jumpVel*dt;if(player.pos.y<=h){player.pos.y=h;jumpVel=0;player.onGround=true}else player.onGround=false;if(keys.ControlLeft||keys.ControlRight)startSlide();if(slideT>0){slideT-=dt;const d=forward();moveXZ(player.pos,d.x*11*dt,d.z*11*dt,.48);if(!keys.ControlLeft&&!keys.ControlRight&&slideT<=0)player.pos.y=1.75}else if(!crouch)player.pos.y=Math.max(player.pos.y,1.75);camera.position.copy(player.pos);const bobAmp=sprinting?.075:moving?.035:0;camera.position.y+=Math.sin(player.bob)*bobAmp;const targetFov=aiming?58:sprinting?84:78;camera.fov+=(targetFov-camera.fov)*Math.min(1,dt*10);camera.updateProjectionMatrix();camera.rotation.set(pitch,yaw,0);const swayX=Math.sin(player.bob*.72)*.018+(s?-.012:0),swayY=Math.cos(player.bob)*.012;viewGun.position.x+=(sprinting?.42:swayX+.38-viewGun.position.x)*Math.min(1,dt*10);viewGun.position.y+=((slideT>0?-.46:crouch?-.43:sprinting?-.38:-.34)+swayY-viewGun.position.y)*Math.min(1,dt*12);viewGun.rotation.z+=(s?-.035:0)-viewGun.rotation.z;viewGun.rotation.x+=(-pitch*.035-(sprinting?.04:0)-viewGun.rotation.x)*Math.min(1,dt*9);if(reloadT>0){const p=1-reloadT/weapons[weaponIndex].reload;viewGun.rotation.x+=Math.sin(p*Math.PI)*.42;viewGun.position.y-=Math.sin(p*Math.PI)*.16}if(fireHeld)shoot()}
function aimAssist(dir){if(!aiming||!enemy?.alive)return dir;const to=enemy.pos.clone().add(new T.Vector3(0,1.35,0)).sub(camera.position),dist=to.length();if(dist>55)return dir;const nd=to.normalize(),dot=dir.dot(nd);if(dot>.975)return dir.lerp(nd,.12*(1-dist/55)).normalize();return dir}
function updateEnemy(dt){if(!enemy||!enemy.alive)return;enemy.phase+=dt*9;enemy.think-=dt;enemy.shoot-=dt;enemy.dodgeT-=dt;const dist=enemy.pos.distanceTo(player.pos),visible=player.alive&&dist<32&&lineClear(enemy.pos,player.pos);if(enemy.think<=0){enemy.think=.14+Math.random()*.16;if(Math.random()<.12)enemy.strafeDir*=-1;enemy.targetPos=visible?player.pos.clone():new T.Vector3((Math.random()-.5)*20,0,(Math.random()-.5)*20)}const dir=enemy.targetPos.clone().sub(enemy.pos);dir.y=0;if(dir.length()>3){dir.normalize();const strafe=new T.Vector3(-dir.z,0,dir.x).multiplyScalar(Math.sin(enemy.phase*1.35)*.85*enemy.strafeDir);const sp=visible?2.7:3.7;moveXZ(enemy.pos,(dir.x+strafe.x)*dt*sp,(dir.z+strafe.z)*dt*sp,.48)}if(visible&&dist<18&&enemy.dodgeT<=0&&Math.random()<dt*.7){enemy.dodgeT=.7;enemy.strafeDir*=-1}enemy.mesh.rotation.y=Math.atan2(-dir.x,-dir.z);const p=enemy.mesh.userData.parts,s=Math.sin(enemy.phase)*.65;p.legL.rotation.x=s;p.legR.rotation.x=-s;p.armL.rotation.x=-s*.18;p.armR.rotation.x=s*.18;if(visible&&enemy.shoot<=0){enemy.shoot=.48+Math.random()*.5;const accuracy=Math.max(.28,.82-dist/50);if(Math.random()<accuracy)enemyShoot()}updateLabel()}
function enemyShoot(){const w=weapons[enemy.weapon],o=enemy.pos.clone();o.y=1.55;const d=player.pos.clone().add(new T.Vector3(0,.2,0)).sub(o).normalize();hitscan(o,d,w,enemy)}
function updateLabel(){if(!enemy?.mesh)return;let t=enemy.mesh.userData.tag;if(!t){t=document.createElement('div');t.className='nameplate enemy';document.getElementById('labels').appendChild(t);enemy.mesh.userData.tag=t}const v=enemy.mesh.position.clone();v.y=2.8;v.project(camera);t.style.transform=`translate(${(v.x*.5+.5)*innerWidth}px,${(-v.y*.5+.5)*innerHeight}px) translate(-50%,-50%)`;t.textContent=enemy.name+'  '+Math.max(0,Math.ceil(enemy.hp))+' HP';t.style.opacity=enemy.alive&&v.z<1?1:0}
function resetRound(){makeArena();player.pos.set(0,1.75,10);player.hp=100;player.armor=50;player.alive=true;player.vel.set(0,0,0);yaw=0;pitch=0;reloadT=0;shootCD=0;aiming=false;fireHeld=false;slideT=0;document.getElementById('cross').classList.remove('aiming');buildMode=false;builds=[];spawnEnemy();ammo=weapons.map(w=>({m:w.mag,r:w.reserve}));phase='shop';buyTime=5;document.getElementById('shop').classList.remove('hidden');renderShop();document.getElementById('hud').classList.remove('hidden');document.getElementById('result').classList.add('hidden');updateHUD();showRoundTitle(round)}
function beginMatch(m){mode=m;round=1;roundWins=0;enemyWins=0;coins=500;player.owned=new Set();weaponIndex=0;running=true;paused=false;document.getElementById('menu').classList.add('hidden');document.getElementById('modeMenu').classList.add('hidden');document.getElementById('queue').classList.add('hidden');initAudio();resetRound()}
function requestLock(){renderer.domElement.requestPointerLock?.()}function playThssh(){playMP3('round',.7)}
function showRoundTitle(n){const el=document.getElementById('roundState');if(!el)return;el.textContent=n===1?'1st ROUND':n===2?'2nd ROUND':n===3?'3rd ROUND':n+'th ROUND';el.classList.add('roundPop');playMP3('round',.7);setTimeout(()=>el.classList.remove('roundPop'),1000)}
function startFight(){if(!player.owned.has(0)){if(coins>=weapons[0].price)coins-=weapons[0].price;player.owned.add(0);weaponIndex=0}phase='fight';roundTime=55;document.getElementById('shop').classList.add('hidden');requestLock();feed('FIGHT!','good');updateHUD()}
function awardRound(won){const reward=won?700:100;coins+=reward;return reward}function finishMatch(){const won=roundWins>enemyWins;phase='result';document.exitPointerLock?.();document.getElementById('resultTitle').textContent=won?'MATCH WON':'MATCH LOST';document.getElementById('resultSub').textContent='5 ROUNDS COMPLETE  •  '+roundWins+' — '+enemyWins+'  •  '+coins+' COINS';document.getElementById('nextRound').textContent='BACK TO MENU';document.getElementById('result').classList.remove('hidden')}
function scheduleNextRound(){if(round>=5){finishMatch();return}roundTransition=setTimeout(()=>{round++;roundTransition=null;resetRound()},850)}
function winRound(head=false){if(phase!=='fight'||!enemy||!enemy.alive)return;enemy.hp=0;enemy.alive=false;phase='transition';roundWins++;coins+=awardRound(true);player.kills++;enemy.mesh.visible=false;document.exitPointerLock?.();feed(head?'HEADSHOT • ROUND WON':'ROUND WON • +700 COINS','good');playMP3('victory',.8);showRoundResult(true);if(round>=5){finishMatch();return}scheduleNextRound()}
function loseRound(){if(phase!=='fight')return;phase='transition';enemyWins++;player.deaths++;player.alive=false;coins+=awardRound(false);document.exitPointerLock?.();feed('ROUND LOST • +100 COINS','bad');playMP3('defeat',.8);showRoundResult(false);if(round>=5){finishMatch();return}scheduleNextRound()}
function nextRound(){if(round>=5){leaveToMenu();return}if(roundTransition){clearTimeout(roundTransition);roundTransition=null}round++;resetRound()}
function leaveToMenu(){if(roundTransition)clearTimeout(roundTransition);running=false;phase='menu';document.exitPointerLock?.();document.getElementById('hud').classList.add('hidden');document.getElementById('result').classList.add('hidden');document.getElementById('pause').classList.add('hidden');document.getElementById('shop').classList.add('hidden');document.getElementById('menu').classList.remove('hidden')}
function renderShop(){const box=document.getElementById('gunCards');document.getElementById('coins').textContent=coins;box.innerHTML='';weapons.forEach((w,i)=>{const owned=player.owned.has(i),selected=i===weaponIndex,can=coins>=w.price||owned;const d=document.createElement('div');d.className='gunCard '+(selected?'selected':'');d.innerHTML=`<div class="gunIcon">${w.icon}</div><h3>${w.name}</h3><div class="stats">PRICE ${w.price} · DMG ${w.damage} · HS ONE-SHOT · MAG ${w.mag}<br>FIRE ${w.rate}/s · RANGE ${w.range} · RELOAD ${w.reload}s</div><button ${can?'':'disabled'}>${owned?(selected?'EQUIPPED':'EQUIP'):'BUY '+w.price}</button>`;d.querySelector('button').onclick=()=>{if(!owned){if(coins<w.price)return;coins-=w.price;player.owned.add(i)}weaponIndex=i;viewGun.clear();viewGun.add(weaponModel(i,true));renderShop();updateHUD()};box.appendChild(d)})}
function updateHUD(){const w=weapons[weaponIndex],a=ammo[weaponIndex]||{m:w.mag,r:w.reserve};document.getElementById('weapon').textContent=w.name;document.getElementById('mag').textContent=a.m;document.getElementById('reserve').textContent=a.r;document.getElementById('hp').textContent=Math.max(0,Math.ceil(player.hp))+' HP';document.getElementById('armor').textContent=Math.max(0,Math.ceil(player.armor))+' ARM';document.getElementById('hpbar').style.width=Math.max(0,player.hp)+'%';document.getElementById('roundScore').textContent=roundWins+' — '+enemyWins;document.getElementById('stance').textContent=slideT>0?'SLIDE':keys.KeyC?'CROUCH':(keys.ShiftLeft||keys.ShiftRight)?'SPRINT':'READY'}
function feed(t,c='neutral'){killFeed.unshift({t,c});killFeed.splice(5);document.getElementById('feed').innerHTML=killFeed.map(x=>`<div class="msg ${x.c}">${x.t}</div>`).join('')}
function setWeapon(i){if(player.owned.has(i)){weaponIndex=i;viewGun.clear();viewGun.add(weaponModel(i,true));updateHUD()}}
function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.05);if(running&&!paused){if(phase==='shop'){buyTime=Math.max(0,buyTime-dt);document.getElementById('buyTimer').textContent=buyTime.toFixed(1);if(buyTime<=0)startFight()}if(phase==='fight'){roundTime-=dt;if(roundTime<=0){roundTime=0;loseRound()}shootCD=Math.max(0,shootCD-dt);if(reloadT>0){reloadT-=dt;if(reloadT<=0){const w=weapons[weaponIndex],a=ammo[weaponIndex],need=w.mag-a.m,take=Math.min(need,a.r);a.m+=take;a.r-=take}}updatePlayer(dt);updateEnemy(dt);document.getElementById('roundTimer').textContent='00:'+String(Math.ceil(roundTime)).padStart(2,'0');updateHUD()}else if(phase==='transition'&&spectating&&enemy?.alive){camera.position.lerp(enemy.pos.clone().add(new T.Vector3(0,1.65,3.2)),Math.min(1,dt*4));camera.lookAt(enemy.pos.clone().add(new T.Vector3(0,1.2,0)))}}if(shake>0){shake-=dt;camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'&&!e.repeat)jump();if(e.code==='KeyR'&&!e.repeat)reload();if((e.code==='ControlLeft'||e.code==='ControlRight')&&!e.repeat)startSlide();if(e.code==='KeyQ'&&!e.repeat){buildMode=!buildMode;document.getElementById('build').classList.toggle('on',buildMode)}if(e.code==='KeyE'&&buildMode)buildRot++;if(e.code==='Digit1')setWeapon(0);if(e.code==='Digit2')setWeapon(1);if(e.code==='Digit3')setWeapon(2);if(e.code==='Digit4')setWeapon(3);if(e.code==='Escape'&&running&&phase==='fight'){paused=true;document.getElementById('pause').classList.remove('hidden');document.exitPointerLock?.()}});addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='ControlLeft'||e.code==='ControlRight'){if(slideT<=0)player.pos.y=1.75}});addEventListener('blur',()=>{for(const k in keys)keys[k]=false;fireHeld=false;aiming=false;document.getElementById('cross').classList.remove('aiming')});addEventListener('mousedown',e=>{if(!running||paused)return;if(phase==='fight'&&!locked)requestLock();if(e.button===0){if(buildMode)placeBuild();else{fireHeld=true;shoot()}}if(e.button===2){if(buildMode){buildMode=false;document.getElementById('build').classList.remove('on')}aiming=true;requestLock();document.getElementById('cross').classList.add('aiming')}});addEventListener('mouseup',e=>{if(e.button===0)fireHeld=false;if(e.button===2){aiming=false;document.getElementById('cross').classList.remove('aiming')}});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(!locked||paused||phase!=='fight'||!player.alive)return;const sens=.0022;yaw-=e.movementX*sens;pitch-=e.movementY*sens;pitch=Math.max(-1.3,Math.min(1.3,pitch))});document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===renderer.domElement);
const show=x=>document.getElementById(x).classList.remove('hidden'),hide=x=>document.getElementById(x).classList.add('hidden');document.getElementById('lonewolf').onclick=()=>{hide('menu');show('modeMenu')};document.getElementById('fightAI').onclick=()=>beginMatch('ai');document.getElementById('fightOnline').onclick=()=>{hide('modeMenu');show('queue');let n=0;const q=setInterval(()=>{n++;document.getElementById('queueText').textContent='Searching… '+(n*20)+'%';if(n>=5){clearInterval(q);document.getElementById('queueTitle').textContent='NO LIVE PLAYER FOUND';document.getElementById('queueText').textContent='Starting a practice opponent so the mode remains playable offline.';setTimeout(()=>beginMatch('online'),800)}},500)};document.getElementById('cancelQueue').onclick=()=>{hide('queue');show('modeMenu')};document.querySelector('[data-back="menu"]').onclick=()=>{hide('modeMenu');show('menu')};document.getElementById('tdm').onclick=()=>alert('Team Arena is kept for the full arena build. 1v1 Lonewolf is the active mode.');document.getElementById('nextRound').onclick=nextRound;document.getElementById('leaveMatch').onclick=leaveToMenu;document.getElementById('resume').onclick=()=>{paused=false;hide('pause');requestLock()};document.getElementById('leavePause').onclick=leaveToMenu;
function jump(){if(phase==='fight'&&player.alive&&player.onGround&&!keys.KeyC&&!slideT){jumpVel=8.2;player.onGround=false}}function placeBuild(){if(!buildMode||phase!=='fight'||!player.alive)return;const p=player.pos.clone().add(forward().multiplyScalar(3));const horizontal=buildRot%2===0,w=horizontal?3.4:.55,d=horizontal?.55:3.4;if(blocked(p.x,p.z,.3)||Math.abs(p.x)>14||Math.abs(p.z)>14)return;const m=addBox(p.x,1.5,p.z,w,3,d,0x657782,true);m.material.transparent=true;m.material.opacity=.9;builds.push({mesh:m});buildMode=false;document.getElementById('build').classList.remove('on')}
makeArena();viewGun.add(weaponModel(0,true));tick();
})();
